### ISSUE TITLE
add interesting boundary conditions.

### ISSUE THREAD

**Issue by windbender** [batman-nair/puddle.js#2]
1)  Something behinds a rectangle ?  Perhaps an oval ?

2) reflection vs absorbtion

**Comment by batman-nair** [comment]
> Something behinds a rectangle ? Perhaps an oval ?

The puddle element takes the shape of the div you give it. Give a circular div and it'll be circular.

> reflection vs absorption

I'm assuming you are meaning at the edges. There are 2 math modes to how forces are calculated. In 'anair' mode, the ripples are more absorbed. i.e doesn't reflect, whereas in 'helias' mode, there is reflection mechanics.
